export const Member = [{
    id: 1,
    fullName: "Otmane ZAHHARI",
    position: "Web Designer",
    img: "../image/profile02.jpg",
    phone: "+212123456",
    email: "oza@oza.oza",
    website: "ozah.com",
  },
  {
    id: 2,
    fullName: "Otmane ZAHHARI",
    position: "Web Designer",
    img: "../image/profile02.jpg",
    phone: "+212123456",
    email: "oza@oza.oza",
    website: "ozah.com",
  },
  {
    id: 3,
    fullName: "Otmane ZAHHARI",
    position: "Web Designer",
    img: "../image/profile02.jpg",
    phone: "+212123456",
    email: "oza@oza.oza",
  },
  {
    id: 4,
    fullName: "Otmane ZAHHARI",
    position: "Web Designer",
    img: "../image/profile02.jpg",
    phone: "+212123456",
    email: "oza@oza.oza",
    website: "ozah.com",
  },
];
// export default Member,